engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
      extensions:
        - .js
        - .json
ratings:
   paths:
   - '*.js'
   - package.json
exclude_paths:
 - commitlint.config.js
 - .eslintrc.js